# -*- coding: utf-8 -*-
"""Linear_RealEstateHW1_Rasel Shikder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyAVyONE7ucwRFmFL1KXJhDCGqPNz072
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm

df = pd.read_csv('/Bootcamp/Real estate.csv')

df.head()

X = df['X2 house age']
y = df['Y house price of unit area']

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

model.summary()

X = df[['X2 house age', 'X3 distance to the nearest MRT station' ]]
y = df['Y house price of unit area']

X = sm.add_constant(X)

model2 = sm.OLS(y, X).fit()

model2.summary()

df.dtypes

X = df.drop(['X1 transaction date', 'Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X = sm.add_constant(X)

model3 = sm.OLS(y, X).fit()

model3.summary()

X = df.drop(['Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X = sm.add_constant(X)

model4 = sm.OLS(y, X).fit()

model4.summary()

X = df.drop(['X1 transaction date', 'X6 longitude', 'Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X = sm.add_constant(X)

model5 = sm.OLS(y, X).fit()

model5.summary()

df.head()

X = df.drop(['No', 'X1 transaction date', 'Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X = sm.add_constant(X)

model6 = sm.OLS(y, X).fit()

model6.summary()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df.drop(['No', 'X1 transaction date', 'Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model7 = LinearRegression()
model7.fit(X_train, y_train)

y_pred = model7.predict(X_test)

import matplotlib.pyplot as plt


plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue', label='Predicted vs. Actual')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', label='Perfect Prediction')
plt.xlabel('Actual Charges')
plt.ylabel('Predicted Charges')
plt.title('Actual vs. Predicted Charges')
plt.legend()
plt.show()

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print performance metrics
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R²): {r2}")

X = df.drop(['X1 transaction date', 'Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model8 = LinearRegression()
model8.fit(X_train, y_train)

y_pred = model8.predict(X_test)

import matplotlib.pyplot as plt


plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue', label='Predicted vs. Actual')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', label='Perfect Prediction')
plt.xlabel('Actual Charges')
plt.ylabel('Predicted Charges')
plt.title('Actual vs. Predicted Charges')
plt.legend()
plt.show()

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print performance metrics
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R²): {r2}")

X = df.drop(['Y house price of unit area'], axis=1)
y = df['Y house price of unit area']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model9 = LinearRegression()
model9.fit(X_train, y_train)

y_pred = model9.predict(X_test)

import matplotlib.pyplot as plt


plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue', label='Predicted vs. Actual')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', label='Perfect Prediction')
plt.xlabel('Actual Charges')
plt.ylabel('Predicted Charges')
plt.title('Actual vs. Predicted Charges')
plt.legend()
plt.show()

r2 = r2_score(y_test, y_pred)

print(f"R-squared (R²): {r2}")